<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Data Tables</title>

    <link href="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/css/plugins/dataTables/datatables.min.css" rel="stylesheet">

    <link href="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/css/animate.css" rel="stylesheet">
    <link href="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/css/style.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <?php 
           /* if(isset($this->vMenu))
            foreach($this->vMenu as $author) {
                echo $author->getMenu();
                echo " ";                
                echo $author->getUrl();
                echo $author->getMenuId();
                echo "<br>";
              }exit(); */
            $menu='<ul>';
            if(isset($this->vMenu))
            foreach($this->vMenu as $n1){
                $menu.="<li><a>".$n1->getMenu()."</a><ul>";
             /*   foreach($mx as $n2 =>$my){
                    if(!empty($n2)){
                        $menu.="<li><a>$n2</a><ul>";
                        foreach($my as $n3 =>$mz){
                            if(!empty($n3)){
                                $menu.="<li><a>$n3</a><ul>";
                                foreach($mz as $nms =>$md)
                                    $menu.="<li><a href=\"$md[id]\">$md[nom]</a></li>";
                                $menu.="</ul></li>";
                            }else
                                foreach($my[$n3] as $nms=>$md)
                                    $menu.="<li><a href=\"$md[id]\">$md[nom]</a></li>";
                        }
                        $menu.="</ul></li>";
                    }else
                        foreach($my[$n2] as $nms=>$md)
                            $menu.="<li><a href=\"$md[id]\">$md[nom]</a></li>";
                } */
                $menu.="</ul></li>";
            }
        $menu.='</ul>';
            ?>
        </div>
    </nav>       

    

        <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
                </li>
                
                


                <li>
                    <a href="<?PHP ECHO Ap_BASE_URL ?>usuario/cerrarSesion">
                        <i class="fa fa-sign-out"></i> Salir
                    </a>
                </li>
            </ul>

        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Menus</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="index.html">Inicio</a>
                        </li>
                        <li>
                            <a>Menus</a>
                        </li>
                        <li class="active">
                            <strong>Listado Menus</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Listado de menus del sistema contable</h5>
                        
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover example" >
                    <thead>
                    <tr>
                        <th>Id Menú</th>
                        <th>Nombre</th>
                        <th>Url</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <?php foreach($this->vMenu as $menu){ ?>
                    <tbody>
                    <tr class="gradeX">
                        <td><?php echo $menu->getMenuId(); ?></td>
                        <td><?php echo $menu->getMenu(); ?>
                        </td>
                        <td><?php echo $menu->getUrl(); ?></td>
                        <td class="center"><?php echo $menu->getEstado(); ?></td>
                        <td class="center">X</td>
                    </tr>
                    <?php } ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>Id Menú</th>
                        <th>Nombre</th>
                        <th>Url</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                    </tfoot>
                    </table>
                        </div>

                    </div>
                </div>
            </div>
            </div>
        </div>
        
        </div>
        </div>



    <!-- Mainly scripts -->
    <script src="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/jquery-3.1.1.min.js"></script>
    <script src="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/bootstrap.min.js"></script>
    <script src="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <script src="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/plugins/dataTables/datatables.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/inspinia.js"></script>
    <script src="<?PHP ECHO Ap_BASE_URL ?>public_/<?PHP ECHO Ap_TEMA_DASHBOARD ?>/js/plugins/pace/pace.min.js"></script>

    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });

    </script>
    <script>
    $(document).ready(function() {
        $('.example').DataTable();
        } );
    </script>

</body>

</html>
